root: true

extends: "airbnb-base"

parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    experimentalObjectRestSpread: true

env:
  browser: true
  es6: true
  jasmine: true
  node: true
